/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Circle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.Circle#getDiameter <em>Diameter</em>}</li>
 * </ul>
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getCircle()
 * @model
 * @generated
 */
public interface Circle extends Stencil
{
  /**
   * Returns the value of the '<em><b>Diameter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Diameter</em>' attribute.
   * @see #setDiameter(float)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getCircle_Diameter()
   * @model
   * @generated
   */
  float getDiameter();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Circle#getDiameter <em>Diameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Diameter</em>' attribute.
   * @see #getDiameter()
   * @generated
   */
  void setDiameter(float value);

} // Circle
