/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Circle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.Circle#getRadius <em>Radius</em>}</li>
 * </ul>
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getCircle()
 * @model
 * @generated
 */
public interface Circle extends Stencil
{
  /**
   * Returns the value of the '<em><b>Radius</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Radius</em>' containment reference.
   * @see #setRadius(Num_value)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getCircle_Radius()
   * @model containment="true"
   * @generated
   */
  Num_value getRadius();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Circle#getRadius <em>Radius</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Radius</em>' containment reference.
   * @see #getRadius()
   * @generated
   */
  void setRadius(Num_value value);

} // Circle
