/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional Shape</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getConditional_Shape()
 * @model
 * @generated
 */
public interface Conditional_Shape extends EObject
{
} // Conditional_Shape
