/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Draw</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.Draw#getFilledColor <em>Filled Color</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.Draw#getPosition <em>Position</em>}</li>
 * </ul>
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getDraw()
 * @model
 * @generated
 */
public interface Draw extends EObject
{
  /**
   * Returns the value of the '<em><b>Filled Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filled Color</em>' containment reference.
   * @see #setFilledColor(Fill)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getDraw_FilledColor()
   * @model containment="true"
   * @generated
   */
  Fill getFilledColor();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Draw#getFilledColor <em>Filled Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filled Color</em>' containment reference.
   * @see #getFilledColor()
   * @generated
   */
  void setFilledColor(Fill value);

  /**
   * Returns the value of the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' containment reference.
   * @see #setPosition(Move)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getDraw_Position()
   * @model containment="true"
   * @generated
   */
  Move getPosition();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Draw#getPosition <em>Position</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' containment reference.
   * @see #getPosition()
   * @generated
   */
  void setPosition(Move value);

} // Draw
