/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Draw</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.Draw#getFilled <em>Filled</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.Draw#getOutlined <em>Outlined</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.Draw#getTransform <em>Transform</em>}</li>
 * </ul>
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getDraw()
 * @model
 * @generated
 */
public interface Draw extends EObject
{
  /**
   * Returns the value of the '<em><b>Filled</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filled</em>' containment reference.
   * @see #setFilled(Filled)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getDraw_Filled()
   * @model containment="true"
   * @generated
   */
  Filled getFilled();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Draw#getFilled <em>Filled</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filled</em>' containment reference.
   * @see #getFilled()
   * @generated
   */
  void setFilled(Filled value);

  /**
   * Returns the value of the '<em><b>Outlined</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outlined</em>' containment reference.
   * @see #setOutlined(Outlined)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getDraw_Outlined()
   * @model containment="true"
   * @generated
   */
  Outlined getOutlined();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Draw#getOutlined <em>Outlined</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Outlined</em>' containment reference.
   * @see #getOutlined()
   * @generated
   */
  void setOutlined(Outlined value);

  /**
   * Returns the value of the '<em><b>Transform</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.online_elm.onlineElm.Tranform}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transform</em>' containment reference list.
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getDraw_Transform()
   * @model containment="true"
   * @generated
   */
  EList<Tranform> getTransform();

} // Draw
