/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage
 * @generated
 */
public interface OnlineElmFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OnlineElmFactory eINSTANCE = org.xtext.online_elm.onlineElm.impl.OnlineElmFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Online Elm</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Online Elm</em>'.
   * @generated
   */
  OnlineElm createOnlineElm();

  /**
   * Returns a new object of class '<em>Main Shape</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Shape</em>'.
   * @generated
   */
  MainShape createMainShape();

  /**
   * Returns a new object of class '<em>Shape Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shape Def</em>'.
   * @generated
   */
  ShapeDef createShapeDef();

  /**
   * Returns a new object of class '<em>Local var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Local var</em>'.
   * @generated
   */
  Local_var createLocal_var();

  /**
   * Returns a new object of class '<em>Shape List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shape List</em>'.
   * @generated
   */
  ShapeList createShapeList();

  /**
   * Returns a new object of class '<em>Basic Shape</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basic Shape</em>'.
   * @generated
   */
  BasicShape createBasicShape();

  /**
   * Returns a new object of class '<em>Shape</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shape</em>'.
   * @generated
   */
  Shape createShape();

  /**
   * Returns a new object of class '<em>Conditional Shape</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conditional Shape</em>'.
   * @generated
   */
  Conditional_Shape createConditional_Shape();

  /**
   * Returns a new object of class '<em>Conditional Color</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conditional Color</em>'.
   * @generated
   */
  Conditional_Color createConditional_Color();

  /**
   * Returns a new object of class '<em>Conditional Num</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conditional Num</em>'.
   * @generated
   */
  Conditional_Num createConditional_Num();

  /**
   * Returns a new object of class '<em>Conditional Str</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conditional Str</em>'.
   * @generated
   */
  Conditional_Str createConditional_Str();

  /**
   * Returns a new object of class '<em>Bool expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bool expr</em>'.
   * @generated
   */
  Bool_expr createBool_expr();

  /**
   * Returns a new object of class '<em>Or expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Or expr</em>'.
   * @generated
   */
  Or_expr createOr_expr();

  /**
   * Returns a new object of class '<em>And expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And expr</em>'.
   * @generated
   */
  And_expr createAnd_expr();

  /**
   * Returns a new object of class '<em>Not expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Not expr</em>'.
   * @generated
   */
  Not_expr createNot_expr();

  /**
   * Returns a new object of class '<em>Compare expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Compare expr</em>'.
   * @generated
   */
  Compare_expr createCompare_expr();

  /**
   * Returns a new object of class '<em>Num value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Num value</em>'.
   * @generated
   */
  Num_value createNum_value();

  /**
   * Returns a new object of class '<em>Math exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Math exp</em>'.
   * @generated
   */
  Math_exp createMath_exp();

  /**
   * Returns a new object of class '<em>Stencil</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stencil</em>'.
   * @generated
   */
  Stencil createStencil();

  /**
   * Returns a new object of class '<em>Circle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Circle</em>'.
   * @generated
   */
  Circle createCircle();

  /**
   * Returns a new object of class '<em>Rect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rect</em>'.
   * @generated
   */
  Rect createRect();

  /**
   * Returns a new object of class '<em>Square</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Square</em>'.
   * @generated
   */
  Square createSquare();

  /**
   * Returns a new object of class '<em>Rounded Rect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rounded Rect</em>'.
   * @generated
   */
  RoundedRect createRoundedRect();

  /**
   * Returns a new object of class '<em>Oval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Oval</em>'.
   * @generated
   */
  Oval createOval();

  /**
   * Returns a new object of class '<em>Ngon</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ngon</em>'.
   * @generated
   */
  Ngon createNgon();

  /**
   * Returns a new object of class '<em>Wedge</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wedge</em>'.
   * @generated
   */
  Wedge createWedge();

  /**
   * Returns a new object of class '<em>Polygon</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Polygon</em>'.
   * @generated
   */
  Polygon createPolygon();

  /**
   * Returns a new object of class '<em>Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Point</em>'.
   * @generated
   */
  Point createPoint();

  /**
   * Returns a new object of class '<em>Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text</em>'.
   * @generated
   */
  Text createText();

  /**
   * Returns a new object of class '<em>Draw</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Draw</em>'.
   * @generated
   */
  Draw createDraw();

  /**
   * Returns a new object of class '<em>Filled</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filled</em>'.
   * @generated
   */
  Filled createFilled();

  /**
   * Returns a new object of class '<em>Outlined</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outlined</em>'.
   * @generated
   */
  Outlined createOutlined();

  /**
   * Returns a new object of class '<em>Tranform</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tranform</em>'.
   * @generated
   */
  Tranform createTranform();

  /**
   * Returns a new object of class '<em>Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move</em>'.
   * @generated
   */
  Move createMove();

  /**
   * Returns a new object of class '<em>Rotate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotate</em>'.
   * @generated
   */
  Rotate createRotate();

  /**
   * Returns a new object of class '<em>Scale</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scale</em>'.
   * @generated
   */
  Scale createScale();

  /**
   * Returns a new object of class '<em>Scale X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scale X</em>'.
   * @generated
   */
  ScaleX createScaleX();

  /**
   * Returns a new object of class '<em>Scale Y</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scale Y</em>'.
   * @generated
   */
  ScaleY createScaleY();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>Float Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Float Literal</em>'.
   * @generated
   */
  FloatLiteral createFloatLiteral();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  OnlineElmPackage getOnlineElmPackage();

} //OnlineElmFactory
