/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Polygon</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.Polygon#getPoint1 <em>Point1</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.Polygon#getPoints <em>Points</em>}</li>
 * </ul>
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getPolygon()
 * @model
 * @generated
 */
public interface Polygon extends Stencil
{
  /**
   * Returns the value of the '<em><b>Point1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point1</em>' containment reference.
   * @see #setPoint1(Point)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getPolygon_Point1()
   * @model containment="true"
   * @generated
   */
  Point getPoint1();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Polygon#getPoint1 <em>Point1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Point1</em>' containment reference.
   * @see #getPoint1()
   * @generated
   */
  void setPoint1(Point value);

  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.online_elm.onlineElm.Point}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getPolygon_Points()
   * @model containment="true"
   * @generated
   */
  EList<Point> getPoints();

} // Polygon
