/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shape List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.ShapeList#getShapeRef <em>Shape Ref</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.ShapeList#getMoreShapes <em>More Shapes</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.ShapeList#getMoreConditional <em>More Conditional</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.ShapeList#getMoreShapeRef <em>More Shape Ref</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.ShapeList#getExternal <em>External</em>}</li>
 * </ul>
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getShapeList()
 * @model
 * @generated
 */
public interface ShapeList extends ShapeDef
{
  /**
   * Returns the value of the '<em><b>Shape Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shape Ref</em>' reference.
   * @see #setShapeRef(BasicShape)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getShapeList_ShapeRef()
   * @model
   * @generated
   */
  BasicShape getShapeRef();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.ShapeList#getShapeRef <em>Shape Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shape Ref</em>' reference.
   * @see #getShapeRef()
   * @generated
   */
  void setShapeRef(BasicShape value);

  /**
   * Returns the value of the '<em><b>More Shapes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.online_elm.onlineElm.Shape}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>More Shapes</em>' containment reference list.
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getShapeList_MoreShapes()
   * @model containment="true"
   * @generated
   */
  EList<Shape> getMoreShapes();

  /**
   * Returns the value of the '<em><b>More Conditional</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.online_elm.onlineElm.Conditional_Shape}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>More Conditional</em>' containment reference list.
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getShapeList_MoreConditional()
   * @model containment="true"
   * @generated
   */
  EList<Conditional_Shape> getMoreConditional();

  /**
   * Returns the value of the '<em><b>More Shape Ref</b></em>' reference list.
   * The list contents are of type {@link org.xtext.online_elm.onlineElm.BasicShape}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>More Shape Ref</em>' reference list.
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getShapeList_MoreShapeRef()
   * @model
   * @generated
   */
  EList<BasicShape> getMoreShapeRef();

  /**
   * Returns the value of the '<em><b>External</b></em>' reference list.
   * The list contents are of type {@link org.xtext.online_elm.onlineElm.ShapeList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>External</em>' reference list.
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getShapeList_External()
   * @model
   * @generated
   */
  EList<ShapeList> getExternal();

} // ShapeList
