/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.Text#getContent <em>Content</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.Text#getConditionalContent <em>Conditional Content</em>}</li>
 * </ul>
 *
 * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getText()
 * @model
 * @generated
 */
public interface Text extends Stencil
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getText_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Text#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

  /**
   * Returns the value of the '<em><b>Conditional Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditional Content</em>' containment reference.
   * @see #setConditionalContent(Conditional_Str)
   * @see org.xtext.online_elm.onlineElm.OnlineElmPackage#getText_ConditionalContent()
   * @model containment="true"
   * @generated
   */
  Conditional_Str getConditionalContent();

  /**
   * Sets the value of the '{@link org.xtext.online_elm.onlineElm.Text#getConditionalContent <em>Conditional Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditional Content</em>' containment reference.
   * @see #getConditionalContent()
   * @generated
   */
  void setConditionalContent(Conditional_Str value);

} // Text
