/*
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.online_elm.ui.internal.Online_elmActivator;

public class OnlineElmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Online_elmActivator.getInstance().getInjector("org.xtext.online_elm.OnlineElm");
	}

}
