/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.online_elm.onlineElm.Bool_expr;
import org.xtext.online_elm.onlineElm.Color;
import org.xtext.online_elm.onlineElm.Conditional_Color;
import org.xtext.online_elm.onlineElm.Conditional_Num;
import org.xtext.online_elm.onlineElm.Conditional_Str;
import org.xtext.online_elm.onlineElm.Local_var;
import org.xtext.online_elm.onlineElm.Num_value;
import org.xtext.online_elm.onlineElm.OnlineElmPackage;
import org.xtext.online_elm.onlineElm.Shape;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bool expr</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getLocal <em>Local</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getRef <em>Ref</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getShape_1 <em>Shape 1</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getNested_1 <em>Nested 1</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getShape_2 <em>Shape 2</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getNested_2 <em>Nested 2</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getColor_1 <em>Color 1</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getColor_2 <em>Color 2</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getNum_1 <em>Num 1</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getNum_2 <em>Num 2</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getStr_1 <em>Str 1</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Bool_exprImpl#getStr_2 <em>Str 2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Bool_exprImpl extends Conditional_ShapeImpl implements Bool_expr
{
  /**
   * The cached value of the '{@link #getLocal() <em>Local</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocal()
   * @generated
   * @ordered
   */
  protected Local_var local;

  /**
   * The default value of the '{@link #getRef() <em>Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRef()
   * @generated
   * @ordered
   */
  protected static final String REF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRef() <em>Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRef()
   * @generated
   * @ordered
   */
  protected String ref = REF_EDEFAULT;

  /**
   * The cached value of the '{@link #getShape_1() <em>Shape 1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShape_1()
   * @generated
   * @ordered
   */
  protected Shape shape_1;

  /**
   * The cached value of the '{@link #getNested_1() <em>Nested 1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNested_1()
   * @generated
   * @ordered
   */
  protected EObject nested_1;

  /**
   * The cached value of the '{@link #getShape_2() <em>Shape 2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShape_2()
   * @generated
   * @ordered
   */
  protected Shape shape_2;

  /**
   * The cached value of the '{@link #getNested_2() <em>Nested 2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNested_2()
   * @generated
   * @ordered
   */
  protected EObject nested_2;

  /**
   * The default value of the '{@link #getColor_1() <em>Color 1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor_1()
   * @generated
   * @ordered
   */
  protected static final Color COLOR_1_EDEFAULT = Color.BLACK;

  /**
   * The cached value of the '{@link #getColor_1() <em>Color 1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor_1()
   * @generated
   * @ordered
   */
  protected Color color_1 = COLOR_1_EDEFAULT;

  /**
   * The default value of the '{@link #getColor_2() <em>Color 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor_2()
   * @generated
   * @ordered
   */
  protected static final Color COLOR_2_EDEFAULT = Color.BLACK;

  /**
   * The cached value of the '{@link #getColor_2() <em>Color 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor_2()
   * @generated
   * @ordered
   */
  protected Color color_2 = COLOR_2_EDEFAULT;

  /**
   * The default value of the '{@link #getNum_1() <em>Num 1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNum_1()
   * @generated
   * @ordered
   */
  protected static final String NUM_1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNum_1() <em>Num 1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNum_1()
   * @generated
   * @ordered
   */
  protected String num_1 = NUM_1_EDEFAULT;

  /**
   * The default value of the '{@link #getNum_2() <em>Num 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNum_2()
   * @generated
   * @ordered
   */
  protected static final String NUM_2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNum_2() <em>Num 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNum_2()
   * @generated
   * @ordered
   */
  protected String num_2 = NUM_2_EDEFAULT;

  /**
   * The default value of the '{@link #getStr_1() <em>Str 1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr_1()
   * @generated
   * @ordered
   */
  protected static final String STR_1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStr_1() <em>Str 1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr_1()
   * @generated
   * @ordered
   */
  protected String str_1 = STR_1_EDEFAULT;

  /**
   * The default value of the '{@link #getStr_2() <em>Str 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr_2()
   * @generated
   * @ordered
   */
  protected static final String STR_2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStr_2() <em>Str 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr_2()
   * @generated
   * @ordered
   */
  protected String str_2 = STR_2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Bool_exprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OnlineElmPackage.Literals.BOOL_EXPR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Local_var getLocal()
  {
    if (local != null && local.eIsProxy())
    {
      InternalEObject oldLocal = (InternalEObject)local;
      local = (Local_var)eResolveProxy(oldLocal);
      if (local != oldLocal)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, OnlineElmPackage.BOOL_EXPR__LOCAL, oldLocal, local));
      }
    }
    return local;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Local_var basicGetLocal()
  {
    return local;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocal(Local_var newLocal)
  {
    Local_var oldLocal = local;
    local = newLocal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__LOCAL, oldLocal, local));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRef()
  {
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRef(String newRef)
  {
    String oldRef = ref;
    ref = newRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__REF, oldRef, ref));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Shape getShape_1()
  {
    return shape_1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetShape_1(Shape newShape_1, NotificationChain msgs)
  {
    Shape oldShape_1 = shape_1;
    shape_1 = newShape_1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__SHAPE_1, oldShape_1, newShape_1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShape_1(Shape newShape_1)
  {
    if (newShape_1 != shape_1)
    {
      NotificationChain msgs = null;
      if (shape_1 != null)
        msgs = ((InternalEObject)shape_1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__SHAPE_1, null, msgs);
      if (newShape_1 != null)
        msgs = ((InternalEObject)newShape_1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__SHAPE_1, null, msgs);
      msgs = basicSetShape_1(newShape_1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__SHAPE_1, newShape_1, newShape_1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getNested_1()
  {
    return nested_1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNested_1(EObject newNested_1, NotificationChain msgs)
  {
    EObject oldNested_1 = nested_1;
    nested_1 = newNested_1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__NESTED_1, oldNested_1, newNested_1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNested_1(EObject newNested_1)
  {
    if (newNested_1 != nested_1)
    {
      NotificationChain msgs = null;
      if (nested_1 != null)
        msgs = ((InternalEObject)nested_1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__NESTED_1, null, msgs);
      if (newNested_1 != null)
        msgs = ((InternalEObject)newNested_1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__NESTED_1, null, msgs);
      msgs = basicSetNested_1(newNested_1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__NESTED_1, newNested_1, newNested_1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Shape getShape_2()
  {
    return shape_2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetShape_2(Shape newShape_2, NotificationChain msgs)
  {
    Shape oldShape_2 = shape_2;
    shape_2 = newShape_2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__SHAPE_2, oldShape_2, newShape_2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShape_2(Shape newShape_2)
  {
    if (newShape_2 != shape_2)
    {
      NotificationChain msgs = null;
      if (shape_2 != null)
        msgs = ((InternalEObject)shape_2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__SHAPE_2, null, msgs);
      if (newShape_2 != null)
        msgs = ((InternalEObject)newShape_2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__SHAPE_2, null, msgs);
      msgs = basicSetShape_2(newShape_2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__SHAPE_2, newShape_2, newShape_2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getNested_2()
  {
    return nested_2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNested_2(EObject newNested_2, NotificationChain msgs)
  {
    EObject oldNested_2 = nested_2;
    nested_2 = newNested_2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__NESTED_2, oldNested_2, newNested_2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNested_2(EObject newNested_2)
  {
    if (newNested_2 != nested_2)
    {
      NotificationChain msgs = null;
      if (nested_2 != null)
        msgs = ((InternalEObject)nested_2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__NESTED_2, null, msgs);
      if (newNested_2 != null)
        msgs = ((InternalEObject)newNested_2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.BOOL_EXPR__NESTED_2, null, msgs);
      msgs = basicSetNested_2(newNested_2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__NESTED_2, newNested_2, newNested_2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Color getColor_1()
  {
    return color_1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColor_1(Color newColor_1)
  {
    Color oldColor_1 = color_1;
    color_1 = newColor_1 == null ? COLOR_1_EDEFAULT : newColor_1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__COLOR_1, oldColor_1, color_1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Color getColor_2()
  {
    return color_2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColor_2(Color newColor_2)
  {
    Color oldColor_2 = color_2;
    color_2 = newColor_2 == null ? COLOR_2_EDEFAULT : newColor_2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__COLOR_2, oldColor_2, color_2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNum_1()
  {
    return num_1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNum_1(String newNum_1)
  {
    String oldNum_1 = num_1;
    num_1 = newNum_1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__NUM_1, oldNum_1, num_1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNum_2()
  {
    return num_2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNum_2(String newNum_2)
  {
    String oldNum_2 = num_2;
    num_2 = newNum_2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__NUM_2, oldNum_2, num_2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStr_1()
  {
    return str_1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStr_1(String newStr_1)
  {
    String oldStr_1 = str_1;
    str_1 = newStr_1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__STR_1, oldStr_1, str_1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStr_2()
  {
    return str_2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStr_2(String newStr_2)
  {
    String oldStr_2 = str_2;
    str_2 = newStr_2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.BOOL_EXPR__STR_2, oldStr_2, str_2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OnlineElmPackage.BOOL_EXPR__SHAPE_1:
        return basicSetShape_1(null, msgs);
      case OnlineElmPackage.BOOL_EXPR__NESTED_1:
        return basicSetNested_1(null, msgs);
      case OnlineElmPackage.BOOL_EXPR__SHAPE_2:
        return basicSetShape_2(null, msgs);
      case OnlineElmPackage.BOOL_EXPR__NESTED_2:
        return basicSetNested_2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OnlineElmPackage.BOOL_EXPR__LOCAL:
        if (resolve) return getLocal();
        return basicGetLocal();
      case OnlineElmPackage.BOOL_EXPR__REF:
        return getRef();
      case OnlineElmPackage.BOOL_EXPR__SHAPE_1:
        return getShape_1();
      case OnlineElmPackage.BOOL_EXPR__NESTED_1:
        return getNested_1();
      case OnlineElmPackage.BOOL_EXPR__SHAPE_2:
        return getShape_2();
      case OnlineElmPackage.BOOL_EXPR__NESTED_2:
        return getNested_2();
      case OnlineElmPackage.BOOL_EXPR__COLOR_1:
        return getColor_1();
      case OnlineElmPackage.BOOL_EXPR__COLOR_2:
        return getColor_2();
      case OnlineElmPackage.BOOL_EXPR__NUM_1:
        return getNum_1();
      case OnlineElmPackage.BOOL_EXPR__NUM_2:
        return getNum_2();
      case OnlineElmPackage.BOOL_EXPR__STR_1:
        return getStr_1();
      case OnlineElmPackage.BOOL_EXPR__STR_2:
        return getStr_2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OnlineElmPackage.BOOL_EXPR__LOCAL:
        setLocal((Local_var)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__REF:
        setRef((String)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__SHAPE_1:
        setShape_1((Shape)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__NESTED_1:
        setNested_1((EObject)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__SHAPE_2:
        setShape_2((Shape)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__NESTED_2:
        setNested_2((EObject)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__COLOR_1:
        setColor_1((Color)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__COLOR_2:
        setColor_2((Color)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__NUM_1:
        setNum_1((String)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__NUM_2:
        setNum_2((String)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__STR_1:
        setStr_1((String)newValue);
        return;
      case OnlineElmPackage.BOOL_EXPR__STR_2:
        setStr_2((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OnlineElmPackage.BOOL_EXPR__LOCAL:
        setLocal((Local_var)null);
        return;
      case OnlineElmPackage.BOOL_EXPR__REF:
        setRef(REF_EDEFAULT);
        return;
      case OnlineElmPackage.BOOL_EXPR__SHAPE_1:
        setShape_1((Shape)null);
        return;
      case OnlineElmPackage.BOOL_EXPR__NESTED_1:
        setNested_1((EObject)null);
        return;
      case OnlineElmPackage.BOOL_EXPR__SHAPE_2:
        setShape_2((Shape)null);
        return;
      case OnlineElmPackage.BOOL_EXPR__NESTED_2:
        setNested_2((EObject)null);
        return;
      case OnlineElmPackage.BOOL_EXPR__COLOR_1:
        setColor_1(COLOR_1_EDEFAULT);
        return;
      case OnlineElmPackage.BOOL_EXPR__COLOR_2:
        setColor_2(COLOR_2_EDEFAULT);
        return;
      case OnlineElmPackage.BOOL_EXPR__NUM_1:
        setNum_1(NUM_1_EDEFAULT);
        return;
      case OnlineElmPackage.BOOL_EXPR__NUM_2:
        setNum_2(NUM_2_EDEFAULT);
        return;
      case OnlineElmPackage.BOOL_EXPR__STR_1:
        setStr_1(STR_1_EDEFAULT);
        return;
      case OnlineElmPackage.BOOL_EXPR__STR_2:
        setStr_2(STR_2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OnlineElmPackage.BOOL_EXPR__LOCAL:
        return local != null;
      case OnlineElmPackage.BOOL_EXPR__REF:
        return REF_EDEFAULT == null ? ref != null : !REF_EDEFAULT.equals(ref);
      case OnlineElmPackage.BOOL_EXPR__SHAPE_1:
        return shape_1 != null;
      case OnlineElmPackage.BOOL_EXPR__NESTED_1:
        return nested_1 != null;
      case OnlineElmPackage.BOOL_EXPR__SHAPE_2:
        return shape_2 != null;
      case OnlineElmPackage.BOOL_EXPR__NESTED_2:
        return nested_2 != null;
      case OnlineElmPackage.BOOL_EXPR__COLOR_1:
        return color_1 != COLOR_1_EDEFAULT;
      case OnlineElmPackage.BOOL_EXPR__COLOR_2:
        return color_2 != COLOR_2_EDEFAULT;
      case OnlineElmPackage.BOOL_EXPR__NUM_1:
        return NUM_1_EDEFAULT == null ? num_1 != null : !NUM_1_EDEFAULT.equals(num_1);
      case OnlineElmPackage.BOOL_EXPR__NUM_2:
        return NUM_2_EDEFAULT == null ? num_2 != null : !NUM_2_EDEFAULT.equals(num_2);
      case OnlineElmPackage.BOOL_EXPR__STR_1:
        return STR_1_EDEFAULT == null ? str_1 != null : !STR_1_EDEFAULT.equals(str_1);
      case OnlineElmPackage.BOOL_EXPR__STR_2:
        return STR_2_EDEFAULT == null ? str_2 != null : !STR_2_EDEFAULT.equals(str_2);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == Conditional_Color.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == Num_value.class)
    {
      switch (derivedFeatureID)
      {
        case OnlineElmPackage.BOOL_EXPR__LOCAL: return OnlineElmPackage.NUM_VALUE__LOCAL;
        case OnlineElmPackage.BOOL_EXPR__REF: return OnlineElmPackage.NUM_VALUE__REF;
        default: return -1;
      }
    }
    if (baseClass == Conditional_Num.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == Conditional_Str.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == Conditional_Color.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == Num_value.class)
    {
      switch (baseFeatureID)
      {
        case OnlineElmPackage.NUM_VALUE__LOCAL: return OnlineElmPackage.BOOL_EXPR__LOCAL;
        case OnlineElmPackage.NUM_VALUE__REF: return OnlineElmPackage.BOOL_EXPR__REF;
        default: return -1;
      }
    }
    if (baseClass == Conditional_Num.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == Conditional_Str.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ref: ");
    result.append(ref);
    result.append(", color_1: ");
    result.append(color_1);
    result.append(", color_2: ");
    result.append(color_2);
    result.append(", num_1: ");
    result.append(num_1);
    result.append(", num_2: ");
    result.append(num_2);
    result.append(", str_1: ");
    result.append(str_1);
    result.append(", str_2: ");
    result.append(str_2);
    result.append(')');
    return result.toString();
  }

} //Bool_exprImpl
