/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.online_elm.onlineElm.Conditional_Num;
import org.xtext.online_elm.onlineElm.OnlineElmPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conditional Num</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Conditional_NumImpl extends Num_valueImpl implements Conditional_Num
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Conditional_NumImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OnlineElmPackage.Literals.CONDITIONAL_NUM;
  }

} //Conditional_NumImpl
