/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.online_elm.onlineElm.BasicShape;
import org.xtext.online_elm.onlineElm.Conditional_Shape;
import org.xtext.online_elm.onlineElm.OnlineElmPackage;
import org.xtext.online_elm.onlineElm.Shape;
import org.xtext.online_elm.onlineElm.ShapeList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Shape List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.ShapeListImpl#getShapeRef <em>Shape Ref</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.ShapeListImpl#getMoreShapes <em>More Shapes</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.ShapeListImpl#getMoreConditional <em>More Conditional</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.ShapeListImpl#getMoreShapeRef <em>More Shape Ref</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.ShapeListImpl#getExternal <em>External</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ShapeListImpl extends ShapeDefImpl implements ShapeList
{
  /**
   * The cached value of the '{@link #getShapeRef() <em>Shape Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShapeRef()
   * @generated
   * @ordered
   */
  protected BasicShape shapeRef;

  /**
   * The cached value of the '{@link #getMoreShapes() <em>More Shapes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoreShapes()
   * @generated
   * @ordered
   */
  protected EList<Shape> moreShapes;

  /**
   * The cached value of the '{@link #getMoreConditional() <em>More Conditional</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoreConditional()
   * @generated
   * @ordered
   */
  protected EList<Conditional_Shape> moreConditional;

  /**
   * The cached value of the '{@link #getMoreShapeRef() <em>More Shape Ref</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoreShapeRef()
   * @generated
   * @ordered
   */
  protected EList<BasicShape> moreShapeRef;

  /**
   * The cached value of the '{@link #getExternal() <em>External</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExternal()
   * @generated
   * @ordered
   */
  protected EList<ShapeList> external;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShapeListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OnlineElmPackage.Literals.SHAPE_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BasicShape getShapeRef()
  {
    if (shapeRef != null && shapeRef.eIsProxy())
    {
      InternalEObject oldShapeRef = (InternalEObject)shapeRef;
      shapeRef = (BasicShape)eResolveProxy(oldShapeRef);
      if (shapeRef != oldShapeRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, OnlineElmPackage.SHAPE_LIST__SHAPE_REF, oldShapeRef, shapeRef));
      }
    }
    return shapeRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BasicShape basicGetShapeRef()
  {
    return shapeRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShapeRef(BasicShape newShapeRef)
  {
    BasicShape oldShapeRef = shapeRef;
    shapeRef = newShapeRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.SHAPE_LIST__SHAPE_REF, oldShapeRef, shapeRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Shape> getMoreShapes()
  {
    if (moreShapes == null)
    {
      moreShapes = new EObjectContainmentEList<Shape>(Shape.class, this, OnlineElmPackage.SHAPE_LIST__MORE_SHAPES);
    }
    return moreShapes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Conditional_Shape> getMoreConditional()
  {
    if (moreConditional == null)
    {
      moreConditional = new EObjectContainmentEList<Conditional_Shape>(Conditional_Shape.class, this, OnlineElmPackage.SHAPE_LIST__MORE_CONDITIONAL);
    }
    return moreConditional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BasicShape> getMoreShapeRef()
  {
    if (moreShapeRef == null)
    {
      moreShapeRef = new EObjectResolvingEList<BasicShape>(BasicShape.class, this, OnlineElmPackage.SHAPE_LIST__MORE_SHAPE_REF);
    }
    return moreShapeRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ShapeList> getExternal()
  {
    if (external == null)
    {
      external = new EObjectResolvingEList<ShapeList>(ShapeList.class, this, OnlineElmPackage.SHAPE_LIST__EXTERNAL);
    }
    return external;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPES:
        return ((InternalEList<?>)getMoreShapes()).basicRemove(otherEnd, msgs);
      case OnlineElmPackage.SHAPE_LIST__MORE_CONDITIONAL:
        return ((InternalEList<?>)getMoreConditional()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OnlineElmPackage.SHAPE_LIST__SHAPE_REF:
        if (resolve) return getShapeRef();
        return basicGetShapeRef();
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPES:
        return getMoreShapes();
      case OnlineElmPackage.SHAPE_LIST__MORE_CONDITIONAL:
        return getMoreConditional();
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPE_REF:
        return getMoreShapeRef();
      case OnlineElmPackage.SHAPE_LIST__EXTERNAL:
        return getExternal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OnlineElmPackage.SHAPE_LIST__SHAPE_REF:
        setShapeRef((BasicShape)newValue);
        return;
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPES:
        getMoreShapes().clear();
        getMoreShapes().addAll((Collection<? extends Shape>)newValue);
        return;
      case OnlineElmPackage.SHAPE_LIST__MORE_CONDITIONAL:
        getMoreConditional().clear();
        getMoreConditional().addAll((Collection<? extends Conditional_Shape>)newValue);
        return;
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPE_REF:
        getMoreShapeRef().clear();
        getMoreShapeRef().addAll((Collection<? extends BasicShape>)newValue);
        return;
      case OnlineElmPackage.SHAPE_LIST__EXTERNAL:
        getExternal().clear();
        getExternal().addAll((Collection<? extends ShapeList>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OnlineElmPackage.SHAPE_LIST__SHAPE_REF:
        setShapeRef((BasicShape)null);
        return;
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPES:
        getMoreShapes().clear();
        return;
      case OnlineElmPackage.SHAPE_LIST__MORE_CONDITIONAL:
        getMoreConditional().clear();
        return;
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPE_REF:
        getMoreShapeRef().clear();
        return;
      case OnlineElmPackage.SHAPE_LIST__EXTERNAL:
        getExternal().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OnlineElmPackage.SHAPE_LIST__SHAPE_REF:
        return shapeRef != null;
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPES:
        return moreShapes != null && !moreShapes.isEmpty();
      case OnlineElmPackage.SHAPE_LIST__MORE_CONDITIONAL:
        return moreConditional != null && !moreConditional.isEmpty();
      case OnlineElmPackage.SHAPE_LIST__MORE_SHAPE_REF:
        return moreShapeRef != null && !moreShapeRef.isEmpty();
      case OnlineElmPackage.SHAPE_LIST__EXTERNAL:
        return external != null && !external.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ShapeListImpl
