/**
 * generated by Xtext 2.24.0
 */
package org.xtext.online_elm.onlineElm.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.online_elm.onlineElm.COMPARISON;
import org.xtext.online_elm.onlineElm.Num_value;
import org.xtext.online_elm.onlineElm.OnlineElmPackage;
import org.xtext.online_elm.onlineElm.Terminal_Bool_exp;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Terminal Bool exp</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Terminal_Bool_expImpl#getN1 <em>N1</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Terminal_Bool_expImpl#getComp <em>Comp</em>}</li>
 *   <li>{@link org.xtext.online_elm.onlineElm.impl.Terminal_Bool_expImpl#getN2 <em>N2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Terminal_Bool_expImpl extends MinimalEObjectImpl.Container implements Terminal_Bool_exp
{
  /**
   * The cached value of the '{@link #getN1() <em>N1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN1()
   * @generated
   * @ordered
   */
  protected Num_value n1;

  /**
   * The default value of the '{@link #getComp() <em>Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComp()
   * @generated
   * @ordered
   */
  protected static final COMPARISON COMP_EDEFAULT = COMPARISON.BIGGER;

  /**
   * The cached value of the '{@link #getComp() <em>Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComp()
   * @generated
   * @ordered
   */
  protected COMPARISON comp = COMP_EDEFAULT;

  /**
   * The cached value of the '{@link #getN2() <em>N2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN2()
   * @generated
   * @ordered
   */
  protected Num_value n2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Terminal_Bool_expImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OnlineElmPackage.Literals.TERMINAL_BOOL_EXP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Num_value getN1()
  {
    return n1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN1(Num_value newN1, NotificationChain msgs)
  {
    Num_value oldN1 = n1;
    n1 = newN1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OnlineElmPackage.TERMINAL_BOOL_EXP__N1, oldN1, newN1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN1(Num_value newN1)
  {
    if (newN1 != n1)
    {
      NotificationChain msgs = null;
      if (n1 != null)
        msgs = ((InternalEObject)n1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.TERMINAL_BOOL_EXP__N1, null, msgs);
      if (newN1 != null)
        msgs = ((InternalEObject)newN1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.TERMINAL_BOOL_EXP__N1, null, msgs);
      msgs = basicSetN1(newN1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.TERMINAL_BOOL_EXP__N1, newN1, newN1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public COMPARISON getComp()
  {
    return comp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComp(COMPARISON newComp)
  {
    COMPARISON oldComp = comp;
    comp = newComp == null ? COMP_EDEFAULT : newComp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.TERMINAL_BOOL_EXP__COMP, oldComp, comp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Num_value getN2()
  {
    return n2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN2(Num_value newN2, NotificationChain msgs)
  {
    Num_value oldN2 = n2;
    n2 = newN2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OnlineElmPackage.TERMINAL_BOOL_EXP__N2, oldN2, newN2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN2(Num_value newN2)
  {
    if (newN2 != n2)
    {
      NotificationChain msgs = null;
      if (n2 != null)
        msgs = ((InternalEObject)n2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.TERMINAL_BOOL_EXP__N2, null, msgs);
      if (newN2 != null)
        msgs = ((InternalEObject)newN2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OnlineElmPackage.TERMINAL_BOOL_EXP__N2, null, msgs);
      msgs = basicSetN2(newN2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OnlineElmPackage.TERMINAL_BOOL_EXP__N2, newN2, newN2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N1:
        return basicSetN1(null, msgs);
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N2:
        return basicSetN2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N1:
        return getN1();
      case OnlineElmPackage.TERMINAL_BOOL_EXP__COMP:
        return getComp();
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N2:
        return getN2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N1:
        setN1((Num_value)newValue);
        return;
      case OnlineElmPackage.TERMINAL_BOOL_EXP__COMP:
        setComp((COMPARISON)newValue);
        return;
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N2:
        setN2((Num_value)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N1:
        setN1((Num_value)null);
        return;
      case OnlineElmPackage.TERMINAL_BOOL_EXP__COMP:
        setComp(COMP_EDEFAULT);
        return;
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N2:
        setN2((Num_value)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N1:
        return n1 != null;
      case OnlineElmPackage.TERMINAL_BOOL_EXP__COMP:
        return comp != COMP_EDEFAULT;
      case OnlineElmPackage.TERMINAL_BOOL_EXP__N2:
        return n2 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (comp: ");
    result.append(comp);
    result.append(')');
    return result.toString();
  }

} //Terminal_Bool_expImpl
